# Generated by Django 4.2.14 on 2024-08-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cookingTime', models.IntegerField()),
                ('ingredients', models.CharField(help_text='Enter the ingredients, separated by a comma', max_length=225)),
            ],
        ),
    ]
