# Generated by Django 4.2.14 on 2024-08-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(help_text='Enter the ingredients, separated by a comma', max_length=255),
        ),
    ]
